### PR TITLE
Add support for the fw API

### PR DESCRIPTION
**Pull request by foreign-sub**
Add:
create_port_forwarding_configuration
delete_port_forwarding_configuration
edit_incoming_port_configuration
get_dmz_configuration
get_incoming_ports_configuration
get_port_forwarding_configuration
set_dmz_configuration

### CODE REVIEW

**Comment by stilllman** [comment]
Thanks!

**Comment by SNoof85** [comment]
Sorry here, i'm late.

Is this not same part like NAT API ?
Some options more for sure but some are now twice in the package.

**Comment by SNoof85** [comment]
I can say that we can delete the NAT because everything from NAT is covered here and not used in Home Assistant.
That will make a breaking change for any other program using aiofreepybox.

**Comment by SNoof85** [comment]
#49 deletes NAT API

**Pull request merged**
